sudo: false
dist: trusty
language: java

cache:
  directories:
  - $HOME/.m2

install:
  - mvn install

script:
 - mvn test -B

deploy:
  provider: script
  script: bash .travis.after_success.sh
  on:
    branch: snapshot


